[build]
builder = "nixpacks"
buildCommand = "npm run build"
watchPatterns = ["."]

[deploy]
startCommand = "npm start"
healthcheckEnabled = false  # Disable health checks entirely
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"
PORT = "8080"